export * from './AboutUs'
export * from './Footer'
export * from '../views/Home'
export * from './Mision'
export * from './OurTeam'
export * from './Projects'
export * from './Services'
export * from './FooterBar'
